// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetHeadlessPreviewPreviewSupportedData, GetHeadlessPreviewPreviewSupportedError, GetHeadlessPreviewPreviewSupportedResponse, GetHeadlessPreviewPreviewUrlInfoData, GetHeadlessPreviewPreviewUrlInfoError, GetHeadlessPreviewPreviewUrlInfoResponse } from './types.gen';

export const client = createClient(createConfig());

export class DocumentService {
    public static getHeadlessPreviewPreviewSupported<ThrowOnError extends boolean = false>(options?: Options<GetHeadlessPreviewPreviewSupportedData, ThrowOnError>) {
        return (options?.client ?? client).get<GetHeadlessPreviewPreviewSupportedResponse, GetHeadlessPreviewPreviewSupportedError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/headless-preview/preview-supported'
        });
    }
    
    public static getHeadlessPreviewPreviewUrlInfo<ThrowOnError extends boolean = false>(options?: Options<GetHeadlessPreviewPreviewUrlInfoData, ThrowOnError>) {
        return (options?.client ?? client).get<GetHeadlessPreviewPreviewUrlInfoResponse, GetHeadlessPreviewPreviewUrlInfoError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/headless-preview/preview-url-info'
        });
    }
    
}