// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetHeadlessPreviewDocumentTypePreviewSupportedData, GetHeadlessPreviewDocumentTypePreviewSupportedError, GetHeadlessPreviewDocumentTypePreviewSupportedResponse, GetHeadlessPreviewDocumentPreviewUrlInfoData, GetHeadlessPreviewDocumentPreviewUrlInfoError, GetHeadlessPreviewDocumentPreviewUrlInfoResponse } from './types.gen';

export const client = createClient(createConfig());

export class DocumentTypeService {
    public static getHeadlessPreviewDocumentTypePreviewSupported<ThrowOnError extends boolean = false>(options?: Options<GetHeadlessPreviewDocumentTypePreviewSupportedData, ThrowOnError>) {
        return (options?.client ?? client).get<GetHeadlessPreviewDocumentTypePreviewSupportedResponse, GetHeadlessPreviewDocumentTypePreviewSupportedError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/headless-preview/document-type/preview-supported'
        });
    }
    
}

export class DocumentService {
    public static getHeadlessPreviewDocumentPreviewUrlInfo<ThrowOnError extends boolean = false>(options?: Options<GetHeadlessPreviewDocumentPreviewUrlInfoData, ThrowOnError>) {
        return (options?.client ?? client).get<GetHeadlessPreviewDocumentPreviewUrlInfoResponse, GetHeadlessPreviewDocumentPreviewUrlInfoError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/headless-preview/document/preview-url-info'
        });
    }
    
}