// This file is auto-generated by @hey-api/openapi-ts

export type DocumentPreviewUrlInfoModel = {
    previewUrl?: string | null;
    info?: string | null;
};

export type GetHeadlessPreviewDocumentTypePreviewSupportedData = {
    body?: never;
    path?: never;
    query?: {
        documentTypeId?: string;
    };
    url: '/umbraco/management/api/v1/headless-preview/document-type/preview-supported';
};

export type GetHeadlessPreviewDocumentTypePreviewSupportedErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetHeadlessPreviewDocumentTypePreviewSupportedResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetHeadlessPreviewDocumentTypePreviewSupportedResponse = GetHeadlessPreviewDocumentTypePreviewSupportedResponses[keyof GetHeadlessPreviewDocumentTypePreviewSupportedResponses];

export type GetHeadlessPreviewDocumentPreviewUrlInfoData = {
    body?: never;
    path?: never;
    query?: {
        documentId?: string;
        culture?: string;
        segment?: string;
    };
    url: '/umbraco/management/api/v1/headless-preview/document/preview-url-info';
};

export type GetHeadlessPreviewDocumentPreviewUrlInfoErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetHeadlessPreviewDocumentPreviewUrlInfoResponses = {
    /**
     * OK
     */
    200: DocumentPreviewUrlInfoModel;
};

export type GetHeadlessPreviewDocumentPreviewUrlInfoResponse = GetHeadlessPreviewDocumentPreviewUrlInfoResponses[keyof GetHeadlessPreviewDocumentPreviewUrlInfoResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44304' | (string & {});
};