// This file is auto-generated by @hey-api/openapi-ts

export type DocumentPreviewUrlInfoModel = {
    previewUrl?: (string) | null;
    info?: (string) | null;
};

export type GetHeadlessPreviewDocumentTypePreviewSupportedData = {
    query?: {
        documentTypeId?: string;
    };
};

export type GetHeadlessPreviewDocumentTypePreviewSupportedResponse = (boolean);

export type GetHeadlessPreviewDocumentTypePreviewSupportedError = (unknown);

export type GetHeadlessPreviewDocumentPreviewUrlInfoData = {
    query?: {
        culture?: string;
        documentId?: string;
        segment?: string;
    };
};

export type GetHeadlessPreviewDocumentPreviewUrlInfoResponse = ((DocumentPreviewUrlInfoModel));

export type GetHeadlessPreviewDocumentPreviewUrlInfoError = (unknown);