// This file is auto-generated by @hey-api/openapi-ts

export type DocumentPreviewUrlInfoModel = {
    previewUrl?: (string) | null;
    info?: (string) | null;
};

export type GetHeadlessPreviewPreviewSupportedData = {
    query?: {
        documentTypeId?: string;
    };
};

export type GetHeadlessPreviewPreviewSupportedResponse = (boolean);

export type GetHeadlessPreviewPreviewSupportedError = (unknown);

export type GetHeadlessPreviewPreviewUrlInfoData = {
    query?: {
        culture?: string;
        documentId?: string;
        segment?: string;
    };
};

export type GetHeadlessPreviewPreviewUrlInfoResponse = ((DocumentPreviewUrlInfoModel));

export type GetHeadlessPreviewPreviewUrlInfoError = (unknown);