// This file is auto-generated by @hey-api/openapi-ts

export const DocumentPreviewUrlInfoModelSchema = {
    type: 'object',
    properties: {
        previewUrl: {
            type: 'string',
            nullable: true
        },
        info: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;