// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetBackOfficePreviewPreviewSupportedData, GetBackOfficePreviewPreviewSupportedError, GetBackOfficePreviewPreviewSupportedResponse, GetBackOfficePreviewPreviewUrlInfoData, GetBackOfficePreviewPreviewUrlInfoError, GetBackOfficePreviewPreviewUrlInfoResponse } from './types.gen';

export const client = createClient(createConfig());

export class DocumentService {
    public static getBackOfficePreviewPreviewSupported<ThrowOnError extends boolean = false>(options?: Options<GetBackOfficePreviewPreviewSupportedData, ThrowOnError>) {
        return (options?.client ?? client).get<GetBackOfficePreviewPreviewSupportedResponse, GetBackOfficePreviewPreviewSupportedError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/back-office-preview/preview-supported'
        });
    }
    
    public static getBackOfficePreviewPreviewUrlInfo<ThrowOnError extends boolean = false>(options?: Options<GetBackOfficePreviewPreviewUrlInfoData, ThrowOnError>) {
        return (options?.client ?? client).get<GetBackOfficePreviewPreviewUrlInfoResponse, GetBackOfficePreviewPreviewUrlInfoError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/back-office-preview/preview-url-info'
        });
    }
    
}