// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetBackOfficePreviewPreviewSupportedData, GetBackOfficePreviewPreviewSupportedError, GetBackOfficePreviewPreviewSupportedResponse, GetBackOfficePreviewPreviewUrlData, GetBackOfficePreviewPreviewUrlError, GetBackOfficePreviewPreviewUrlResponse } from './types.gen';

export const client = createClient(createConfig());

export class ContentService {
    public static getBackOfficePreviewPreviewSupported<ThrowOnError extends boolean = false>(options?: Options<GetBackOfficePreviewPreviewSupportedData, ThrowOnError>) {
        return (options?.client ?? client).get<GetBackOfficePreviewPreviewSupportedResponse, GetBackOfficePreviewPreviewSupportedError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/back-office-preview/preview-supported'
        });
    }
    
    public static getBackOfficePreviewPreviewUrl<ThrowOnError extends boolean = false>(options?: Options<GetBackOfficePreviewPreviewUrlData, ThrowOnError>) {
        return (options?.client ?? client).get<GetBackOfficePreviewPreviewUrlResponse, GetBackOfficePreviewPreviewUrlError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/back-office-preview/preview-url'
        });
    }
    
}