// This file is auto-generated by @hey-api/openapi-ts

export type GetBackOfficePreviewPreviewSupportedData = {
    query?: {
        documentTypeId?: string;
    };
};

export type GetBackOfficePreviewPreviewSupportedResponse = (boolean);

export type GetBackOfficePreviewPreviewSupportedError = (unknown);

export type GetBackOfficePreviewPreviewUrlData = {
    query?: {
        culture?: string;
        documentId?: string;
    };
};

export type GetBackOfficePreviewPreviewUrlResponse = (string);

export type GetBackOfficePreviewPreviewUrlError = (unknown);