// This file is auto-generated by @hey-api/openapi-ts

export type DocumentPreviewUrlInfoModel = {
    previewUrl?: (string) | null;
    info?: (string) | null;
};

export type GetBackOfficePreviewPreviewSupportedData = {
    query?: {
        documentTypeId?: string;
    };
};

export type GetBackOfficePreviewPreviewSupportedResponse = (boolean);

export type GetBackOfficePreviewPreviewSupportedError = (unknown);

export type GetBackOfficePreviewPreviewUrlInfoData = {
    query?: {
        culture?: string;
        documentId?: string;
        segment?: string;
    };
};

export type GetBackOfficePreviewPreviewUrlInfoResponse = ((DocumentPreviewUrlInfoModel));

export type GetBackOfficePreviewPreviewUrlInfoError = (unknown);